# Generated by Django 5.0.6 on 2024-05-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test_created_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog')], default='cat', max_length=50, null=True),
        ),
    ]
